apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 3005
        env:
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: uri
        - name: SMTP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: credentials
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 3005
  type: ClusterIP 