apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: food-delivery
data:
  MONGODB_URI: "mongodb://mongodb:27017/order-service"
  NODE_ENV: "development"
  ORDER_SERVICE_PORT: "5001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: order-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-delivery
spec:
  selector:
    app: order-service
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP 