apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-ordering-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: food-ordering-system
spec:
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 3003
  type: ClusterIP 