apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-mgmt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-mgmt
  template:
    metadata:
      labels:
        app: restaurant-mgmt
    spec:
      containers:
      - name: app
        image: your-docker-repo/restaurant-mgmt:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/restaurantdb
        - name: JWT_SECRET
          value: your_jwt_secret